- domain: .work.weixin.qq.com
  httpOnly: false
  name: wxpay.vid
  path: /
  secure: false
  value: '1688855099238847'
- domain: .work.weixin.qq.com
  httpOnly: false
  name: wxpay.corpid
  path: /
  secure: false
  value: '1970324971499789'
- domain: .work.weixin.qq.com
  httpOnly: false
  name: wwrtx.vid
  path: /
  secure: false
  value: '1688855099238847'
- domain: .work.weixin.qq.com
  httpOnly: true
  name: wwrtx.ref
  path: /
  secure: false
  value: direct
- domain: .work.weixin.qq.com
  httpOnly: true
  name: wwrtx.ltype
  path: /
  secure: false
  value: '1'
- domain: .work.weixin.qq.com
  httpOnly: false
  name: wwrtx.d2st
  path: /
  secure: false
  value: a7873325
- domain: .work.weixin.qq.com
  httpOnly: true
  name: wwrtx.logined
  path: /
  secure: false
  value: 'true'
- domain: .qq.com
  expiry: 1631028066
  httpOnly: false
  name: _gid
  path: /
  secure: false
  value: GA1.2.2124018933.1630941657
- domain: .work.weixin.qq.com
  httpOnly: true
  name: wwrtx.refid
  path: /
  secure: false
  value: '16572563021254191'
- domain: .work.weixin.qq.com
  httpOnly: false
  name: wwrtx.cs_ind
  path: /
  secure: false
  value: ''
- domain: .qq.com
  expiry: 1630941717
  httpOnly: false
  name: _gat
  path: /
  secure: false
  value: '1'
- domain: .work.weixin.qq.com
  expiry: 1662477655.592035
  httpOnly: false
  name: wwrtx.c_gdpr
  path: /
  secure: false
  value: '0'
- domain: .qq.com
  expiry: 1694013666
  httpOnly: false
  name: _ga
  path: /
  secure: false
  value: GA1.2.1788866072.1630941657
- domain: .work.weixin.qq.com
  httpOnly: true
  name: wwrtx.sid
  path: /
  secure: false
  value: uJ2ZJIwBwpuNIeSpRIpE7aAkclL-bR1vFfcsK012RdeBu9GQx7TkJGegFkTSCuG3
- domain: .work.weixin.qq.com
  httpOnly: true
  name: wwrtx.vst
  path: /
  secure: false
  value: 0A2jxCbAOukrQbcAnX7V_CJ_wbA8971TdqnoakHIoCUTx0yOWDEngnvAVoUhGWr6_M7cWlcpe6DSbC1gfJ3Bki8vcG8IoT73FJ8t11EllVjCLSvPyo2ElRpl6VmAVtTwo547zdf1BqKMw9wd_WyfTI7cc8R6MhWpgmtiNX3wjwR8dCA_uqjfgAvC-cYvSIkzgnB9sD7XWC10T9QcKlTIouDWiK2P5VO0wqczLpRkF8kVhJqHx0sP1ulFcy-ZdPkv1umSShQfMW9dQVRsYicgEA
- domain: .work.weixin.qq.com
  expiry: 1633533669.071544
  httpOnly: false
  name: wwrtx.i18n_lan
  path: /
  secure: false
  value: zh
